#!/usr/bin/env bash
#
# TEL caller
#____________________________________________________________________
# contacts functions


main() {

    [[ "$1" == "-h" ]] && {
        printf  "%s\n"\
                "call [OPTIONS]"\
                "__________________________"\
                "OPTIONS"\
                "  -h   Display this help"\
                "  -u   Update contact list"
        exit 0
    }

    contactsfile="$HOME/.contacts";

    [[ ! -a "$contactsfile" || "$1" == '-u' ]] && {
        termux-contact-list > "$contactsfile"_temp
        sleep 2
    }

     # get the nuber from the selected contact
    number=$(fzf < "$contactsfile" | cut -d "|" -f2)

    #kills the program if termux-telephony-call command is not available
    ( command -v termux-telephony-call >/dev/null 2>&1 ) || { 
         printf "\e[38;5;1m[!]%s\n\e[m"\
               "termux-telephony-call not available"\
               "Install TEL-API app and termux-api package"
        exit 1
    }

    termux-telephony-call "$number"
}

main "$@"