#!/usr/bin/env bash
printf '\e[38;5;6m'
printf '██████  ██████  ██████  ██              ██████  ██████  ██    \n'
printf '██████  ██  ██  ██████  ██                ██    ████    ██    \n'
printf '██  ██  ██  ██  ██  ██  ██████  ██████    ██    ██████  ██████\n'
printf '\e[m'

# status_function
print_install_status() {
    printf -- '\e[38;5;6m[*] %s\e[m\n' "$*"
}

# error_printing_function
print_error_and_die() {
    printf -- '\e[38;5;9m[ERR] %s\e[m\n' "$*"
    exit 1
}

# 
get_shell() {
    rc="${HOME}/.${SHELL##*/}rc"

    [ ! -f "$rc" ] &&
       rc="${HOME}/.profile"
}

# set motd on end of install
set_motd() {
    :> ~/../usr/etc/motd
    printf  "%s\n"\
            "██████  ██████  ██    "\
            "  ██    ████    ██    "\
            "  ██    ██████  ██████" >> ~/../usr/etc/motd
}

upgrade_mnml_tel() {
    print_install_status "upgrading minimal_tel"

    # cd into ~/.mnml_tel
    cd "$HOME/.minimal_tel" || print_error_and_die "Where the frick is $HOME/.minimal_tel"
    
    ( git pull --rebase --stat origin master ) || {
        print_error_and_die "something went wrong with the upgrade"
    }
    
    print_install_status "upgraded minimal_tel"
}

install_mnml_tel() {
    pkg install git fzf termux-api
    
    print_install_status "installing mnml_tel"
    
    git clone 'https://github.com/Sidd-Dino/minimal_tel.git' .minimal_tel ||\
    print_error_and_die "could not clone the git repository"\
                        " 'https://github.com/Sidd-Dino/minimal_tel.git'";
    
    get_shell
    echo 'export PATH="$PATH:$HOME/.minimal_tel/"' >> "$rc"
    echo '. ~/.mnml_tel/aliases' >> "$rc"

    set_motd
}

main() {
    # Preserve path
    old_pwd="$PWD"

    cd "$HOME" ||\
        print_error_and_die "Couldn't cd into home"

    # If .mnml_tel already exists upgrade mnml_tel
    [[ -d "$HOME/.minimal_tel" ]] && upgrade_mnml_tel

    # If .mnml_tel doesn't exist install mnml_tel
    [[ -a "$HOME/.minimal_tel" ]] || install_mnml_tel

    cd "$old_pwd" ||\
        print_error_and_die "Couldn't cd back to intial directory"
}

main