#!/usr/bin/env bash

oldifs=$IFS
IFS=$'\n'
battery_info=( "$(termux-battery-status)" )

for line in "${battery_info[@]}"; do
    [[ "$line" == *"percentage"* ]] &&{
        bat_capacity="${line//*percentage\": /}"
        bat_capacity="${bat_capacity:: -1}"
    }

    [[ "$line" == *"percentage"* ]] &&{
        bat_status="${line//*status\": /}"
        bat_status="${bat_status::1}"
    }
done

IFS=$oldifs

printf  '[ DATE ] %(%a %d %b)T\n' '-1'
printf  '[ TIME ] %(%H:%M)T\n' '-1'
printf  '[ BATT ] %s %s\n' "$bat_capacity" "$bat_status"