#!/usr/bin/env bash

exec 9<> termux-battery-status
while IFS=$'\n' read -r line; do
    [[ $line == *"percentage"* ]] && bat_capacity="${line//*percentage\": /}"
    [[ $line == *"status"* ]] && bat_status="${line//*status\": \"/}"
done <9

bat_capacity="${bat_capacity:: -1}"
bat_status="${bat_status:: 1}"

printf  '[ DATE ] %(%a %d %b)T\n' '-1'
printf  '[ TIME ] %(%H:%M)T\n' '-1'
printf  '[ BATT ] %s %s\n' "${bat_capacity}" "${bat_status}"