#!/usr/bin/env bash

termux-battery-status > ~/.temp

while IFS=$'\n' read -rs line; do
    [[ "$line" == *"percentage"* ]] &&{
        bat_capacity="${line//*percentage\": /}"
        bat_capacity="${bat_capacity:: -1}"
    }

    [[ "$line" == *"percentage"* ]] &&{
        bat_status="${line//*status\": /}"
        bat_status="${bat_status::1}"
    }
done

printf  '[ DATE ] %(%a %d %b)T\n' '-1'
printf  '[ TIME ] %(%H:%M)T\n' '-1'
printf  '[ BATT ] %s %s\n' "$bat_capacity" "$bat_status"

rm ~/.temp